### ISSUE TITLE
customize some faces for company-mode 

### ISSUE THREAD

**Issue by stardiviner** [madhat2r/madhat2r-theme#1]
![madhat2r-theme company](https://cloud.githubusercontent.com/assets/378699/22531005/7ca33f74-e919-11e6-910c-c4431e9395c5.png)

The following two faces are missing just like in upper screenshot. The annotation can's see.

- `company-tooltip-annotation-selection`
- `company-tooltip-search-selection`

**Comment by madhat2r** [comment]
Thanks for reporting this issue @stardiviner . 

I was not very happy with the way company looked anyway, it felt a bit out of place with the rest of the theme, so I took this oporitunity to make it blend a bit better, while also addressing the two faces you mentioned.

I hope you like the change!

**Comment by stardiviner** [comment]
After test, I think the company-tooltip-selection face should be more different with default background dark color.

**Comment by madhat2r** [comment]
@stardiviner , I can agree with that. I have updated now, and I think you are correct it does make it a bit better.

**Comment by stardiviner** [comment]
confirmed. Thanks.
